name: Build and push xsuite Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

env:
  IMAGE_REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/xsuite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check the recent xsuite version
        id: ver
        run: |
           echo "version=$(python3 ci/check_recent_pypi_version.py)" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check
        env:
          RECENT_XSUITE_VERSION: ${{ steps.ver.outputs.version }}
        run: |
            python3 ci/check_docker_tag.py

      - name: Build and push
        if: steps.check.outputs.tag_exists == 'false'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            XSUITE_VERSION=${{ steps.ver.outputs.version }}
          tags: |
            ${{ env.IMAGE_REPO }}:${{ steps.ver.outputs.version }}
            ${{ env.IMAGE_REPO }}:latest
