name: Build and push xsuite Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

env:
  IMAGE_REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/xsuite

jobs:
  build-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor:
          - name: cpu
            file: Dockerfile
            tag_suffix: ""
          - name: opencl
            file: Dockerfile.opencl
            tag_suffix: "-opencl"
    
    outputs:
      tag_exists: ${{ steps.check.outputs.tag_exists }}
      version: ${{ steps.ver.outputs.version }}
      minor_version: ${{ steps.ver.outputs.minor_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check the recent xsuite version
        id: ver
        run: |
           python3 ci/check_recent_pypi_version.py

      - name: Check if tag exists
        id: check
        env:
          RECENT_XSUITE_VERSION: ${{ steps.ver.outputs.version }}
          RECENT_MINOR_VERSION: ${{ steps.ver.outputs.minor_version }}
        run: |
            python3 ci/check_docker_tag.py

      - name: Build and push
        if: steps.check.outputs.tag_exists == 'false'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.flavor.file }}
          push: true
          build-args: |
            XSUITE_VERSION=${{ steps.ver.outputs.version }}
          tags: |
            ${{ env.IMAGE_REPO }}:${{ steps.ver.outputs.minor_version }}${{ matrix.flavor.tag_suffix }}
            ${{ env.IMAGE_REPO }}:latest${{ matrix.flavor.tag_suffix }}

  build-hpc:
    runs-on: ubuntu-latest
    needs: build-base

    if: needs.build-base.outputs.tag_exists == 'false'

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.hpc
          push: true
          build-args: |
            XSUITE_VERSION=${{ needs.build-base.outputs.version }}
          tags: |
            ${{ env.IMAGE_REPO }}:${{ needs.build-base.outputs.minor_version }}-gsihpc
            ${{ env.IMAGE_REPO }}:latest-gsihpc